version: '3.8'

services:
  media-cleaner:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: media-cleaner
    environment:
      # SONARR_URL: "http://sonarr:8989"
      # SONARR_API_KEY: "your_sonarr_api_key"
      # SONARR_STALL_LIMIT: "5"
      # SONARR_AUTO_SEARCH: "false"  
      # RADARR_URL: "http://radarr:7878"
      # RADARR_API_KEY: "your_radarr_api_key"
      # RADARR_STALL_LIMIT: "5"
      # RADARR_AUTO_SEARCH: "false"  
      LIDARR_URL: "http://172.24.1.241:8686/api/v1"
      LIDARR_API_KEY: ""
      # LIDARR_STALL_LIMIT: "5"
      LIDARR_AUTO_SEARCH: "true"  
      API_TIMEOUT: "30"
      GLOBAL_STALL_LIMIT: "3"
      DEBUG_LOGGING: "true"
    volumes:
      - "./data:/app/data"  # Ensure this path aligns with the STRIKE_FILE_PATH in your script
    restart: unless-stopped
