version: '3.8'

services:
  media-cleaner:
    image: media-cleaner
    container_name: media-cleaner
    environment:
      SONARR_API_KEY: "your_sonarr_api_key"
      RADARR_API_KEY: "your_radarr_api_key"
      SONARR_URL: "http://sonarr:8989"
      RADARR_URL: "http://radarr:7878"
      API_TIMEOUT: "3600"  # Set to check every hour
      STALL_COUNT_LIMIT: "3" # Number of checks before grabbing different release
      RESET_STRIKES_ON_PROGRESS: "all" # Number of strikes to remove from stall count when release is not stalled
    volumes:
      - "./data:/app/data"  # Ensure this path aligns with the STRIKE_FILE_PATH in your script
    restart: unless-stopped
